package com.ultimatedungeon.room.templates;

import com.ultimatedungeon.room.model.RoomData;
import com.ultimatedungeon.room.model.RoomType;
import com.ultimatedungeon.theme.model.ThemeBlockPalette;
import org.bukkit.Location;
import org.bukkit.Material;
import org.jetbrains.annotations.NotNull;

import java.util.ArrayDeque;
import java.util.Collections;
import java.util.Deque;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

/**
 * Room template: MazeRoomTemplate (MAZE).
 *
 * <p>A large room whose interior is filled with a perfect maze generated by the
 * recursive-backtracker algorithm. Walls are two blocks tall so players must
 * weave through the passages. The floor, ceiling and outer shell come from
 * {@link AbstractRoomTemplate#buildHollowBox}; this class only carves the maze
 * into the interior.</p>
 */
public final class MazeRoomTemplate extends AbstractRoomTemplate {

    private static final int SIZE = 21; // odd so the maze grid lines up with the walls

    public MazeRoomTemplate() {
        super("maze", RoomType.MAZE, 6);
    }

    @Override public int getWidth()  { return SIZE; }
    @Override public int getDepth()  { return SIZE; }
    @Override public int getHeight() { return 6; }

    @Override
    protected void decorateRoom(
            @NotNull final Location          origin,
            @NotNull final RoomData          data,
            @NotNull final ThemeBlockPalette palette
    ) {
        final int w = getWidth();
        final int d = getDepth();
        final Material wall = palette.getPrimary();

        // 1) Fill the whole interior with two-tall walls.
        for (int x = 1; x < w - 1; x++) {
            for (int z = 1; z < d - 1; z++) {
                placeRelative(origin, x, 1, z, wall);
                placeRelative(origin, x, 2, z, wall);
            }
        }

        // 2) Recursive-backtracker carve on the odd-coordinate cell grid.
        final boolean[][] carved = new boolean[w][d];
        final Deque<int[]> stack = new ArrayDeque<>();
        carveCell(origin, 1, 1, carved);
        stack.push(new int[]{1, 1});

        while (!stack.isEmpty()) {
            final int[] cur = stack.peek();
            final List<int[]> dirs = new java.util.ArrayList<>(List.of(
                    new int[]{2, 0}, new int[]{-2, 0}, new int[]{0, 2}, new int[]{0, -2}));
            Collections.shuffle(dirs, ThreadLocalRandom.current());

            boolean advanced = false;
            for (final int[] dir : dirs) {
                final int nx = cur[0] + dir[0];
                final int nz = cur[1] + dir[1];
                if (nx < 1 || nx > w - 2 || nz < 1 || nz > d - 2) continue;
                if (carved[nx][nz]) continue;
                // Knock down the wall between the current cell and the neighbour.
                carveCell(origin, cur[0] + dir[0] / 2, cur[1] + dir[1] / 2, carved);
                carveCell(origin, nx, nz, carved);
                stack.push(new int[]{nx, nz});
                advanced = true;
                break;
            }
            if (!advanced) stack.pop();
        }

        // 3) Scatter a few ceiling lights so the maze is not pitch black.
        for (int x = 3; x < w - 1; x += 6) {
            for (int z = 3; z < d - 1; z += 6) {
                placeRelative(origin, x, getHeight() - 1, z, Material.GLOWSTONE);
            }
        }
    }

    /** Clears a single maze cell to a two-tall air passage. */
    private void carveCell(@NotNull final Location origin, final int x, final int z,
                           final boolean[][] carved) {
        placeRelative(origin, x, 1, z, Material.AIR);
        placeRelative(origin, x, 2, z, Material.AIR);
        carved[x][z] = true;
    }
}
